### ISSUE TITLE
Fix Chrome spin buttons

### ISSUE THREAD

**Issue by VovanR** [VovanR/when-to-go-from-work#5]
```css
input[type=time]::-webkit-inner-spin-button,
input[type=time]::-webkit-outer-spin-button {
  display: block;
  height: 100%;
  width: 32px;
}
```
